[tool.poetry]
name = "dlmm"
version = "0.1.0"
description = ""
authors = ["Tanishq Parkar <tanishqparkar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
solders = "^0.27.1"
solana = "^0.36.11"
requests = "^2.32.5"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
